services:
  app:
    image: nanawel/cliup
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      # Make sure you create the folder with the write permissions for 1000:1000
      - ./uploads:/uploads
    environment:
      MEMORY_LIMIT: 256M
      # 2 days
      EXPIRATION_TIME: 172800
      # 200 MB
      MAX_UPLOAD_FILESIZE: 209715200
      # 200 MB + 512B (overhead)
      POST_MAX_SIZE: 209715712
